name: spaces
description: Defining global spacing constants for building consistent and responsive apps.
version: 0.5.0
homepage: https://github.com/aloisdeniel/spaces

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  gap: ^2.0.0-nullsafety.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3

dev_dependencies:
  freezed: 2.3.2
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter

flutter:
