name: spaces
description: Defining global spacing constants for building consistent and responsive apps.
version: 0.6.0
homepage: https://github.com/aloisdeniel/spaces

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  gap: ^2.0.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  build_runner: any
  flutter_lints: any
